<h1>3D Truss Analysis Example</h1>
<p>This document demonstrates using Jupyter for vector operations by determinging the axial forces in a simple 3D space truss.</p>

In [13]:
from numpy import *
from scipy.linalg import *
from IPython.display import display
X=0
Y=1
Z=2

In [2]:
a=array((1.1, -0.4, 0))
b=array((1,0,0))
c=array((0,0,0.6))
d=array((0,0,-0.4))
e=array((0,0.8,0))

In [3]:
def λ(a,b):
    return (b-a)/norm(b-a)
λab=λ(a,b)
λac=λ(a,c)
λad=λ(a,d)
print(λab, '\n',λac,'\n', λad)

[-0.24253563  0.9701425   0.        ] 
 [-0.83631451  0.30411437  0.45617155] 
 [-0.88929729  0.32338083 -0.32338083]


In [4]:
m=matrix(((λab[X],λac[X],λad[X]),
          (λab[Y],λac[Y],λad[Y]),
          (λab[Z],λac[Z],λad[Z])))
m

matrix([[-0.24253563, -0.83631451, -0.88929729],
        [ 0.9701425 ,  0.30411437,  0.32338083],
        [ 0.        ,  0.45617155, -0.32338083]])

In [5]:
minv=inv(m)
minv

array([[  4.12310563e-01,   1.13385405e+00,   1.51255974e-17],
       [ -5.26117858e-01,  -1.31529464e-01,   1.31529464e+00],
       [ -7.42159013e-01,  -1.85539753e-01,  -1.23693169e+00]])

In [6]:
(TAB, TAC, TAD)=dot(minv,array((0,-40,0))).tolist()
(TAB, TAC, TAD)

(-45.35416188179428, 5.261178575186367, 7.421590126111796)

<h2>Joint B</h2>

In [7]:
λba=λ(b,a)
λbc=λ(b,c)
λbd=λ(b,d)
λbe=λ(b,e)
print(λba, '\n',λbc,'\n', λbd,'\n', λbe)

[ 0.24253563 -0.9701425   0.        ] 
 [-0.85749293  0.          0.51449576] 
 [-0.92847669  0.         -0.37139068] 
 [-0.78086881  0.62469505  0.        ]


In [8]:
m=matrix(((λbc[X],λbd[X],λbe[X]),
          (λbc[Y],λbd[Y],λbe[Y]),
          (λbc[Z],λbd[Z],λbe[Z])))
m

matrix([[-0.85749293, -0.92847669, -0.78086881],
        [ 0.        ,  0.        ,  0.62469505],
        [ 0.51449576, -0.37139068,  0.        ]])

In [9]:
minv=inv(m)
minv

array([[-0.46647615, -0.58309519,  1.16619038],
       [-0.64621978, -0.80777472, -1.07703296],
       [ 0.        ,  1.60078106,  0.        ]])

In [10]:
TAB * λba

array([-11.,  44.,  -0.])

In [11]:
(TBC, TBD, TBE)=dot(minv,-TAB * λba).tolist()
(TBC, TBD, TBE)

(20.524950669855468, 28.43367018167018, -70.43436661176136)

<h2>Joint E</h2>

In [14]:
λeb=-λbe
display(λeb)
m=identity(3)
m

array([ 0.78086881, -0.62469505, -0.        ])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
minv=inv(m)
minv

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

In [16]:
TBE * λeb

array([-55.,  44.,   0.])

In [22]:
E=dot(minv,-TBE * λeb)
E

array([ 55., -44.,   0.])

<h2>Joint C</h2>

In [26]:
λca=-λac
λcb=-λbc

In [28]:
print(TAC * λca, '\n', TBC * λcb)

[ 4.4 -1.6 -2.4] 
 [ 17.6   -0.   -10.56]


In [31]:
C=dot(minv,-(TAC * λca+TBC * λcb))
C

array([-22.  ,   1.6 ,  12.96])

<h2>Joint D</h2>

In [33]:
λda=-λad
λdb=-λbd

In [34]:
D=dot(minv,-(TAD * λda + TBD * λdb))
D

array([-33.  ,   2.4 , -12.96])

In [36]:
C + D + E

array([  0.00000000e+00,  -4.00000000e+01,   3.55271368e-15])