# Using Numpy Matrix Class
This notebook is very similar to [the same problem](Statics_Problem.ipynb) solved using plain numpy arrays for the matrices and vectors.  The difference is that this notebook uses [numpy.matrix](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html#numpy-matrix) for the matrices and vectors.  I, [Will Holmes](http://www.linkedin.com/in/will-holmes), prefer the method in [the other notebook](Statics_Problem.ipynb).  While using the numpy.matrix class is more mathematically correct, I like the simplicity of the notation and not having to take transposes.  I guess the main thing I dislike about the formalism in this notebook is the fact that to get the element of vector, I still have to use a two dimensional index.  For example, the x component of the unit vector $\lambda_{AB}$ is given by $\lambda\_AB[X,0]$ rather than $\lambda\_AB[X]$.   

In [1]:
#import stuff for working with matrices.
from numpy import *
#Set printing of numpy items to 3 decimal points.
set_printoptions(precision = 3)
#Use X, Y, Z for matrix indexing.
X, Y, Z =(0, 1, 2)

#Define function for calculating unit vector from given input vector.
def λ(v):
    return v/sqrt(v.T.dot(v))

# Problem 3.50 (Statics by Hibbler 6<sup>th</sup> Edition)
<img src="Statics_Problem.png" style="float:right;width:3.5in;">Using the figure to the right, determine the tensions in cables AB and AC. The
applied force F is $500\ lbf$, $F = 500\ lbf$, and the tension in cable AD
is 210 lbf, $T_{\text{AD}} = 210\ lbf$. For this problem, you must complete
the following steps.
1.  Determine the unit vectors AB and AC and AD
2.  Write down force equilibrium conditions for point A.
3.  Clearly Indicate the two equations you need to solve to determine the
    tensions $T_{AB}$ and $T_{AC}$. This may be in matrix form
    or as written out equations.
4.  Solve your two equations for $T_{AB}$ and $T_{AC}$ using
    whatever method you wish.
5.  In step 2, you should have written down three equations for force
    equilibrium at point A. You then used two of them to solve for
    $T_{AB}$ and $T_{AC}$. Check your answers for
    $T_{AB}$ and $T_{AC}$ using the third equation. Clearly indicate if your answer is correct or incorrect. If it is incorrect and time remains, correct your errors.

## Problem Overview
The fundamental idea for this problem is to complete a free body diagram for point A.  In this case, we have one applied force and a known cable tension force.  Even though this is a 3D FBD which can give us three equilibrium equations, we only need two equations to solve the problem.  We will use two equations and then use the third as a check of our work.  Our Equilibrium Equation is then:
$$F_{AB}\lambda_{AB}+F_{AC}\lambda_{AC}+F_{AD}\lambda_{AD}+F_{app}=0$$

## Unit Vectors
To solve this, we first need to determine the unit vectors.  To find the unit vectors we write down the points, find the position vectors, and then find the unit vectors.

*Note in the cell below, the points A,B,C and D are the column vectors.  The purpose of the [.T](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.T.html#numpy.matrix.T) after the call to [matrix](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html) is to take the [transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.T.html#numpy.matrix.T) since the vector was entered as a row vector (There first matrix index has only one item).  The .T turns the 1 X 3 matrix into a 3 X 1 matrix.  The .T in the print statement is to print results as a row since this is more compact.*

In [2]:
A=matrix([ 0,  0,  6]).T
B=matrix([3,  -2,  0]).T
C=matrix([-3, -1,  0]).T
D=matrix([-2,  3,  0]).T
λ_AB=λ(B-A)
λ_AC=λ(C-A)
λ_AD=λ(D-A)
print("The unit vectors are:\n λ_AB=",λ_AB.T,"\n λ_AC=",λ_AC.T,"\n λ_AD=",λ_AD.T)

The unit vectors are:
 λ_AB= [[ 0.429 -0.286 -0.857]] 
 λ_AC= [[-0.442 -0.147 -0.885]] 
 λ_AD= [[-0.286  0.429 -0.857]]


## Applied Forces
We are given values for the applied force and $T_{AD}$.

In [3]:
F_app=matrix([0, 0, 500]).T
print("F_app is:\n",F_app.T)
T_AD=210
F_AD=T_AD*λ_AD
print("\nF_AD is:\n",F_AD.T)

F_app is:
 [[  0   0 500]]

F_AD is:
 [[ -60.   90. -180.]]


## Equilibrium
The equilibrium equation, $F_{AB}\lambda_{AB}+F_{AC}\lambda_{AC}+F_{AD}\lambda_{AD}+F_{app}=0$, is then:

$$\mathbf{M} \left[ \begin{array}{c}T_{AB}\\T_{AC}\end{array} \right] = -F_{app} - F_{AD}$$

Using the x and y equations, the matrix $\mathbf{M}$ is defined below.

In [4]:
M=matrix([[λ_AB[X, 0],λ_AC[X, 0]],
          [λ_AB[Y, 0],λ_AC[Y, 0]]])
print(M)

[[ 0.429 -0.442]
 [-0.286 -0.147]]


The RHS, $-F_{app} - F_{AD}$, is

In [5]:
RHS=matrix([-F_app[X,0]-F_AD[X,0],-F_app[Y,0]-F_AD[Y,0]]).T
RHS

matrix([[ 60.],
        [-90.]])

## Solution
The inverse of $\mathbf{M}$ is:

In [6]:
print(M.I)

[[ 0.778 -2.333]
 [-1.507 -2.261]]


The solution for the tensions, $T_{AB}$ and $T_{AC}$, is then:

In [7]:
solutions=M.I.dot(RHS)
T_AB, T_AC =[solutions[0,0],solutions[1,0]]
print('The solution is\n T_AB = ',T_AB,'\n T_AC = ',T_AC)

The solution is
 T_AB =  256.666666667 
 T_AC =  113.038833052


We can check our solution using equilibrium in the z direction.  Our Z eqation is:
$$F_{AB}\lambda_{AB}+F_{AC}\lambda_{AC}+F_{AD}\lambda_{AD}+F_{app}=0$$

In [8]:
T_AB*λ_AB[Z,0]+T_AC*λ_AC[Z,0]+T_AD*λ_AD[Z,0]+F_app[Z,0]

0.0

Since the above equation does give zero, the system is in equilibrium in the z direction.  Note that we could also run this check with all the equations as shown below.

In [9]:
T_AB*λ_AB+T_AC*λ_AC+T_AD*λ_AD+F_app

matrix([[ 0.],
        [ 0.],
        [ 0.]])