In [1]:
#import stuff for working with matrices.
from numpy import *
from numpy.linalg import inv
#Set printing of numpy items to 3 decimal points.
set_printoptions(precision = 3)
#Use X, Y, Z for matrix indexing.
X, Y, Z =(0, 1, 2)

#Define function for calculating unit vector from given input vector.
def λ(v):
    return v/sqrt(v.dot(v))

# Problem 3.50 (Statics by Hibbler 6<sup>th</sup> Edition)
<img src="Statics_Problem.png" style="float:right;width:3.5in;">Using the figure to the right, determine the tensions in cables AB and AC. The
applied force F is $500\ lbf$, $F = 500\ lbf$, and the tension in cable AD
is 210 lbf, $T_{\text{AD}} = 210\ lbf$. For this problem, you must complete
the following steps.
1.  Determine the unit vectors AB and AC and AD
2.  Write down force equilibrium conditions for point A.
3.  Clearly Indicate the two equations you need to solve to determine the
    tensions $T_{AB}$ and $T_{AC}$. This may be in matrix form
    or as written out equations.
4.  Solve your two equations for $T_{AB}$ and $T_{AC}$ using
    whatever method you wish.
5.  In step 2, you should have written down three equations for force
    equilibrium at point A. You then used two of them to solve for
    $T_{AB}$ and $T_{AC}$. Check your answers for
    $T_{AB}$ and $T_{AC}$ using the third equation. Clearly indicate if your answer is correct or incorrect. If it is incorrect and time remains, correct your errors.

## Problem Overview
The fundamental idea for this problem is to complete a free body diagram for point A.  In this case, we have one applied force and a known cable tension force.  Even though this is a 3D FBD which can give us three equilibrium equations, we only need two equations to solve the problem.  We will use two equations and then use the third as a check of our work.  Our Equilibrium Equation is then:
$$F_{AB}\lambda_{AB}+F_{AC}\lambda_{AC}+F_{AD}\lambda_{AD}+F_{app}=0$$

## Unit Vectors
To solve this, we first need to determine the unit vectors.  To find the unit vectors we write down the points, find the position vectors, and then find the unit vectors.

In [2]:
A=array([ 0,  0,  6])
B=array([3,  -2,  0])
C=array([-3, -1,  0])
D=array([-2,  3,  0])
λ_AB=λ(B-A)
λ_AC=λ(C-A)
λ_AD=λ(D-A)
print("The unit vectors are:\n λ_AB=",λ_AB,"\n λ_AC=",λ_AC,"\n λ_AD=",λ_AD)

The unit vectors are:
 λ_AB= [ 0.429 -0.286 -0.857] 
 λ_AC= [-0.442 -0.147 -0.885] 
 λ_AD= [-0.286  0.429 -0.857]


## Applied Forces
We are given values for the applied force and $T_{AD}$.

In [3]:
F_app=array([0, 0, 500.])
print("F_app is:\n",F_app)
T_AD=210
F_AD=T_AD*λ_AD
print("\nF_AD is:\n",F_AD)

F_app is:
 [   0.    0.  500.]

F_AD is:
 [ -60.   90. -180.]


## Equilibrium
The equilibrium equation, $F_{AB}\lambda_{AB}+F_{AC}\lambda_{AC}+F_{AD}\lambda_{AD}+F_{app}=0$, is then:

$$\mathbf{M} \left[ \begin{array}{c}T_{AB}\\T_{AC}\end{array} \right] = -F_{app} - F_{AD}$$

Using the x and y equations, the matrix $\mathbf{M}$ is defined below.

In [4]:
M=array([[λ_AB[X],λ_AC[X]],
          [λ_AB[Y],λ_AC[Y]]])
print(M)

[[ 0.429 -0.442]
 [-0.286 -0.147]]


The matrix $\mathbf{M}$ could also be formed using the [numpy stack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html#numpy.stack) function to combine the unit vectors into an array.  The code below does this and gives the same result as above.  The code `axis=-1` tells stack to place the columns side by side rather than as one long array.  The code `[0:2,:]` is a [python slice](http://stackoverflow.com/a/509295/6854613) and returns only the x and y components.

In [5]:
M=stack((λ_AB,λ_AC),axis=-1)[0:2,:]
print(M)

[[ 0.429 -0.442]
 [-0.286 -0.147]]


The RHS, $-F_{app} - F_{AD}$, is

In [6]:
RHS=(-F_app-F_AD)[0:2]
RHS

array([ 60., -90.])

## Solution
The inverse of $\mathbf{M}$ is:

In [7]:
print(inv(M))

[[ 0.778 -2.333]
 [-1.507 -2.261]]


The solution for the tensions, $T_{AB}$ and $T_{AC}$, is then:

In [8]:
solutions=inv(M).dot(RHS)
T_AB, T_AC =[solutions[0],solutions[1]]
print('The solution is\n T_AB = ',T_AB,'\n T_AC = ',T_AC)

The solution is
 T_AB =  256.666666667 
 T_AC =  113.038833052


We can check our solution using equilibrium in the z direction.  Our Z eqation is:
$$F_{AB}\lambda_{AB}+F_{AC}\lambda_{AC}+F_{AD}\lambda_{AD}+F_{app}=0$$

In [9]:
T_AB*λ_AB[Z]+T_AC*λ_AC[Z]+T_AD*λ_AD[Z]+F_app[Z]

0.0

Since the above equation does give zero, the system is in equilibrium in the z direction.  Note that we could also run this check with all the equations as shown below.

In [10]:
T_AB*λ_AB+T_AC*λ_AC+T_AD*λ_AD+F_app

array([ 0.,  0.,  0.])